export enum UserConstante {
  USER_WITH_ONE_SUBSCRIPTION = "USER_WITH_ONE_SUBSCRIPTION",
  USER_WITH_MULTIPLE_SUBSCRIPTION = "USER_WITH_MULTIPLE_SUBSCRIPTION",
  USER_WITHOUT_SUBSCRIPTION = "USER_WITHOUT_SUBSCRIPTION",
}
